---
- name: install jdk
  apt:
    name: openjdk-8-jdk
    state: present
#- name : set java_home 
# shell: 'export JAVA_HOME="{{ JAVA_HOME }}" >>/.bashrc'

- name: Add tomcat group
  group:
    name: tomcat
    system: true
    state: present

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Create a tomcat directory
  file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat
- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /usr/share/tomcat
    mode: 0755
    owner: tomcat
    group: tomcat
    creates: /usr/share/tomcat/bin
   
